Rails:
  Enabled: true

inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 25

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'node_modules/**/*'


